name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Deno Deployでの認証に必要です。
      contents: read # リポジトリのクローンに必要です。

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: dhal
          entrypoint: server/entry.mjs
          root: dist
